CREATE TABLE PINACOTECAS (
	ID_PINACOTECA	NUMBER(10),
	NOMBRE			VARCHAR2(15),
	DIRECCION		VARCHAR2(50),
	CIUDAD			VARCHAR2(15),
	PAIS			VARCHAR2(15),
	SUPERFICIE		NUMBER(10),
	CONSTRAINT pk_pinacotecas PRIMARY KEY (ID_PINACOTECA)
	);
COMMIT;

CREATE TABLE CUADROS (

	ID_CUADRO		NUMBER(10),
	N_CUADRO		VARCHAR2(15),
	ANCHO			NUMBER(5),
	ALTO			NUMBER(5),
	F_PINTADO		DATE,
	TECNICA			VARCHAR2(15),
	FK_PINAC		NUMBER(10),

	CONSTRAINT pk_cuadros PRIMARY KEY (ID_CUADRO),
	CONSTRAINT fk_cuadro FOREIGN KEY (FK_PINAC) REFERENCES PINACOTECAS

	);

COMMIT;

CREATE TABLE PINTORES (
	
	ID_PINTOR		NUMBER(10),
	N_PINTOR		VARCHAR2(15),
	CIUDAD			VARCHAR2(15),
	PAIS			VARCHAR2(15),
	FECHA_N			DATE,
	FECHA_F			DATE,

	CONSTRAINT pk_pintores PRIMARY KEY (ID_PINTOR)

	);
	
COMMIT;

CREATE TABLE CUADROS_PINTORES (

	ID_FK_CUADRO	NUMBER(10),
	FK_PINTOR		NUMBER(10),

	CONSTRAINT pk_cuadros_pintores PRIMARY KEY (ID_FK_CUADRO),
	CONSTRAINT fk1_cuadros_cp FOREIGN KEY (ID_FK_CUADRO) REFERENCES CUADROS,
	CONSTRAINT fk2_pintores_cp FOREIGN KEY (FK_PINTOR) REFERENCES PINTORES

	);

COMMIT;

CREATE TABLE ESCUELAS (

	ID_ESCUELA		NUMBER(10),
	N_ESCUELA		VARCHAR2(20),
	PAIS			VARCHAR2(15),
	FECHA_APARICION	DATE,

	CONSTRAINT pk_escuelas PRIMARY KEY (ID_ESCUELA)

	);
	
COMMIT;

CREATE TABLE PINTORES-ESCUELAS (

	ID_FK_PINTOR	NUMBER(10),
	FK_ESCUELA		NUMBER(10),

	CONSTRAINT pk_cuadros_pintores PRIMARY KEY (ID_FK_PINTOR),
	CONSTRAINT fk1_pintores_pe FOREIGN KEY (ID_FK_PINTOR) REFERENCES PINTORES,
	CONSTRAINT fk2_escuelas_pe FOREIGN KEY (FK_ESCUELA) REFERENCES ESCUELAS

	);
	
COMMIT;

CREATE TABLE MECENAS (

	ID_MECENAS	NUMBER(10),
	N_MECENAS	VARCHAR2(15),
	CIUDAD_NAC	VARCHAR2(15),
	PAIS		VARCHAR2(15),
	
	CONSTRAINT pk_mecenas PRIMARY KEY (ID_MECENAS)

	);

COMMIT;

CREATE TABLE MECENAZGO (

	ID_FK_PINTOR	NUMBER(10),
	ID_FK_MECENAS	NUMBER(10),
	ID_FECHA_INICIO	DATE,
	FECHA_FINAL		DATE,
	
	CONSTRAINT pk1_mecenazgo PRIMARY KEY (ID_FK_PINTOR),
	CONSTRAINT pk2_mecenazgo PRIMARY KEY (ID_FK_MECENAS),
	CONSTRAINT fk1_pintores_m FOREIGN KEY (ID_PINTOR) REFERENCES PINTORES,
	CONSTRAINT fk2_mecenas_m FOREIGN KEY (ID_MECENAS) REFERENCES MECENAS

	);

COMMIT;

CREATE TABLE MAESTROS (

	ID_FK_PINTOR	NUMBER(10),
	FK_MAESTRO		NUMBER(10),

	CONSTRAINT pk_maestros PRIMARY KEY (ID_FK_PINTORES),
	CONSTRAINT fk_pintor_m FOREIGN KEY (ID_PINTOR) REFERENCES PINTORES

	);

COMMIT;