CREATE TABLESPACE PINACOTECAS1
DATAFILE
  'C:\ORACLE\EJEMPLOS\PINACOTECAS1\PINACOTECAS1-1.ORA' SIZE 1 M,
  'C:\ORACLE\EJEMPLOS\PINACOTECAS1\PINACOTECAS1-2.ORA' SIZE 500 K
DEFAULT STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 25);

CREATE USER PINACOTECAS1
IDENTIFIED BY PINACOTECAS1
DEFAULT TABLESPACE PINACOTECAS1
QUOTA UNLIMITED ON PINACOTECAS1;
COMMIT;
GRANT DBA TO PINACOTECAS1;
COMMIT;
CONNECT PINACOTECAS1;