CREATE TABLE ACTORES (
CODIGO NUMBER,
NOMBRE VARCHAR2(50),
FECHA DATE,
NACIONALIDAD VARCHAR2(20),
CONSTRAINT pk_actores PRIMARY KEY (CODIGO)
);
COMMIT;
CREATE TABLE PERSONAJES (
CODIGO NUMBER,
NOMBRE VARCHAR2(50),
RAZA VARCHAR2(20),
GRADO VARCHAR2(20),
CODIGO_ACTOR NUMBER,
CODIGO_SUPERIOR NUMBER,
CONSTRAINT pk_personajes PRIMARY KEY (CODIGO),
CONSTRAINT fk1_actores FOREIGN KEY (CODIGO_ACTOR) REFERENCES ACTORES (CODIGO),
CONSTRAINT fk2_personajes FOREIGN KEY (CODIGO_SUPERIOR) REFERENCES PERSONAJES (CODIGO)
);
COMMIT;
CREATE TABLE PLANETAS (
CODIGO NUMBER,
GALAXIA VARCHAR2(50),
NOMBRE VARCHAR2(50),
CONSTRAINT pk_planetas PRIMARY KEY (CODIGO)
);
COMMIT;
CREATE TABLE CAPITULOS (
TEMPORADA NUMBER,
ORDEN NUMBER,
TITULO VARCHAR2(50),
FECHA DATE,
CONSTRAINT pk_capitulos PRIMARY KEY (TEMPORADA,ORDEN)
);
COMMIT;
CREATE TABLE PELICULAS (
CODIGO NUMBER,
TUTULO VARCHAR2(50),
DIRECTOR VARCHAR2(30),
YEAR DATE,
CONSTRAINT pk_peliculas PRIMARY KEY (CODIGO)
);
COMMIT;
CREATE TABLE PERSONAJES_CAPITULOS (
CODIGO_PERSONAJE NUMBER,
TEMPORADA NUMBER,
ORDEN NUMBER,
CONSTRAINT pk_personajes_capitulos PRIMARY KEY (CODIGO_PERSONAJE,TEMPORADA,ORDEN),
CONSTRAINT fk1_personajes FOREIGN KEY (CODIGO_PERSONAJE) REFERENCES PERSONAJES (CODIGO),
CONSTRAINT fk2_capitulos FOREIGN KEY (TEMPORADA,ORDEN) REFERENCES CAPITULOS (TEMPORADA,ORDEN)
);
COMMIT;
CREATE TABLE PERSONAJES_PELICULAS (
CODIGO_PERSONAJE NUMBER,
CODIGO_PELICULA NUMBER,
CONSTRAINT pk_personajes_peliculas PRIMARY KEY (CODIGO_PERSONAJE,CODIGO_PELICULA),
CONSTRAINT fk1_personajes_p FOREIGN KEY (CODIGO_PERSONAJE) REFERENCES PERSONAJES (CODIGO),
CONSTRAINT fk2_peliculas FOREIGN KEY (CODIGO_PELICULA) REFERENCES PELICULAS (CODIGO)
);
COMMIT;
CREATE TABLE NAVES (
CODIGO NUMBER,
N_TRIPULANTES NUMBER,
NOMBRE VARCHAR2(50),
CONSTRAINT pk_naves PRIMARY KEY (CODIGO)
);
COMMIT;
CREATE TABLE VISITAS (
CODIGO_NAVE NUMBER,
CODIGO_PLANETA NUMBER,
TEMPORADA NUMBER,
ORDEN NUMBER,
CONSTRAINT pk_visitas PRIMARY KEY (CODIGO_NAVE,CODIGO_PLANETA,TEMPORADA,ORDEN),
CONSTRAINT fk1_naves FOREIGN KEY (CODIGO_NAVE) REFERENCES NAVES (CODIGO),
CONSTRAINT fk2_planetas FOREIGN KEY (CODIGO_PLANETA) REFERENCES PLANETAS (CODIGO),
CONSTRAINT fk3_capitulos FOREIGN KEY (TEMPORADA,ORDEN) REFERENCES CAPITULOS (TEMPORADA,ORDEN)
);
COMMIT;

