CREATE TABLESPACE STARTREK
DATAFILE
  'C:\ORACLE\EJEMPLOS\STARTREK\STARTREK-1.ORA' SIZE 1 M,
  'C:\ORACLE\EJEMPLOS\STARTREK\STARTREK-2.ORA' SIZE 500 K
DEFAULT STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 25);

CREATE USER STARTREK
IDENTIFIED BY STARTREK
DEFAULT TABLESPACE STARTREK
QUOTA UNLIMITED ON STARTREK;
COMMIT;
GRANT DBA TO STARTREK;
COMMIT;
CONNECT STARTREK;