CREATE TABLESPACE STARTREK
DATAFILE
  'C:\ORACLE\EJEMPLOS\STARTREK\STARTREK-1.ORA' SIZE 1 M,
  'C:\ORACLE\EJEMPLOS\STARTREK\STARTREK-2.ORA' SIZE 500 K
DEFAULT STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 25);

CREATE USER STARTREK
IDENTIFIED BY STARTREK
DEFAULT TABLESPACE STARTREK
QUOTA UNLIMITED ON STARTREK;
COMMIT;
GRANT DBA TO STARTREK;
COMMIT;
CONNECT STARTREK
CREATE TABLE ACTORES (
CODIGO NUMBER,
NOMBRE VARCHAR2(50) NOT NULL,
FECHA DATE,
NACIONALIDAD VARCHAR2(20),
CONSTRAINT pk_actores PRIMARY KEY (CODIGO)
);
COMMIT;
CREATE TABLE PERSONAJES (
CODIGO NUMBER,
NOMBRE VARCHAR2(50) NOT NULL,
RAZA VARCHAR2(20) NOT NULL,
GRADO VARCHAR2(20) NOT NULL,
CODIGO_ACTOR NUMBER,
CODIGO_SUPERIOR NUMBER,
CONSTRAINT pk_personajes PRIMARY KEY (CODIGO)
);
COMMIT;
CREATE TABLE PLANETAS (
CODIGO NUMBER,
GALAXIA VARCHAR2(50) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
CONSTRAINT pk_planetas PRIMARY KEY (CODIGO)
);
COMMIT;
CREATE TABLE CAPITULOS (
TEMPORADA NUMBER,
ORDEN NUMBER,
TITULO VARCHAR2(50) NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT pk_capitulos PRIMARY KEY (TEMPORADA,ORDEN)
);
COMMIT;
CREATE TABLE PELICULAS (
CODIGO NUMBER,
TUTULO VARCHAR2(50) NOT NULL,
DIRECTOR VARCHAR2(30) NOT NULL,
YEAR DATE,
CONSTRAINT pk_peliculas PRIMARY KEY (CODIGO)
);
COMMIT;
CREATE TABLE PERSONAJES_CAPITULOS (
CODIGO_PERSONAJE NUMBER,
TEMPORADA NUMBER,
ORDEN NUMBER,
CONSTRAINT pk_personajes_capitulos PRIMARY KEY (CODIGO_PERSONAJE,TEMPORADA,ORDEN)
);
COMMIT;
CREATE TABLE PERSONAJES_PELICULAS (
CODIGO_PERSONAJE NUMBER,
CODIGO_PELICULA NUMBER,
CONSTRAINT pk_personajes_peliculas PRIMARY KEY (CODIGO_PERSONAJE,CODIGO_PELICULA)
);
COMMIT;
CREATE TABLE NAVES (
CODIGO NUMBER,
N_TRIPULANTES NUMBER NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
CONSTRAINT pk_naves PRIMARY KEY (CODIGO)
);
COMMIT;
CREATE TABLE VISITAS (
CODIGO_NAVE NUMBER,
CODIGO_PLANETA NUMBER,
TEMPORADA NUMBER,
ORDEN NUMBER,
CONSTRAINT pk_visitas PRIMARY KEY (CODIGO_NAVE,CODIGO_PLANETA,TEMPORADA,ORDEN)
);
COMMIT;
ALTER TABLE PERSONAJES ADD CONSTRAINT fk1_actores FOREIGN KEY (CODIGO_ACTOR) REFERENCES ACTORES (CODIGO);
ALTER TABLE PERSONAJES ADD CONSTRAINT fk2_personajes FOREIGN KEY (CODIGO_SUPERIOR) REFERENCES PERSONAJES (CODIGO);
ALTER TABLE PERSONAJES_CAPITULOS ADD CONSTRAINT fk1_personajes FOREIGN KEY (CODIGO_PERSONAJE) REFERENCES PERSONAJES (CODIGO);
ALTER TABLE PERSONAJES_CAPITULOS ADD CONSTRAINT fk2_capitulos FOREIGN KEY (TEMPORADA,ORDEN) REFERENCES CAPITULOS (TEMPORADA,ORDEN);
ALTER TABLE PERSONAJES_PELICULAS ADD CONSTRAINT fk1_personajes_p FOREIGN KEY (CODIGO_PERSONAJE) REFERENCES PERSONAJES (CODIGO);
ALTER TABLE PERSONAJES_PELICULAS ADD CONSTRAINT fk2_peliculas FOREIGN KEY (CODIGO_PELICULA) REFERENCES PELICULAS (CODIGO);
ALTER TABLE VISITAS ADD CONSTRAINT fk1_naves FOREIGN KEY (CODIGO_NAVE) REFERENCES NAVES (CODIGO);
ALTER TABLE VISITAS ADD CONSTRAINT fk2_planetas FOREIGN KEY (CODIGO_PLANETA) REFERENCES PLANETAS (CODIGO);
ALTER TABLE VISITAS ADD CONSTRAINT fk3_capitulos FOREIGN KEY (TEMPORADA,ORDEN) REFERENCES CAPITULOS (TEMPORADA,ORDEN);
COMMIT;