CREATE TABLESPACE EXAMEN
DATAFILE
 'C:\ORACLE\EJEMPLOS\EXAMEN\EXAMEN-1.ORA' SIZE 1 M,
 'C:\ORACLE\EJEMPLOS\EXAMEN\EXAMEN-2.ORA' SIZE 500 K
DEFAULT STORAGE (...);

CREATE USER EXAMEN
IDENTIFIED BY EXAMEN
DEFAULT TABLESPACE EXAMEN
QUOTA UNLIMITED ON EXAMEN;
COMMIT;
GRANT DBA TO EXAMEN;
COMMIT;

CREATE TABLE CLIENTES (
CODIGO NUMBER,
DIRECCION VARCHAR2(40),
TELEFONO NUMBER,
-- RESTRICCIONES CLAVE PRIMARIA Y FORANEAS
CONSTRAINT pk_clientes PRIMARY KEY (CODIGO)
);
COMMIT;

CREATE TABLE PROYECTOS (
CODIGO NUMBER,
DESCRIPCION VARCHAR2(50),
CUANTIA NUMBER,
FECHA_INICIO DATE,
FECHA_FIN DATE,
CODIGO_CLIENTE NUMBER,
-- RESTRICCIONES CLAVE PRIMARIA Y FORANEAS
CONSTRAINT pk_proyectos PRIMARY KEY (CODIGO),
CONSTRAINT fk_clientes FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES (CODIGO)
);
COMMIT;

CREATE TABLE COLABORADORES (
NIF VARCHAR2(9),
NOMBRE VARCHAR2(10),
APELLIDOS VARCHAR2(20),
DOMICILIO VARCHAR2(20),
TELEFONO NUMBER,
BANCO VARCHAR2(10),
NUMERO_CUENTA NUMBER,
-- RESTRICCIONES CLAVE PRIMARIA Y FORANEAS
CONSTRAINT pk_colaboradores PRIMARY KEY (NIF)
);
COMMIT;

CREATE TABLE COLABORACIONES (
CODIGO_PROYECTOS NUMBER,
NIF_COLABORADOR VARCHAR2(9),
-- RESTRICCIONES CLAVE PRIMARIA Y FORANEAS
CONSTRAINT pk_colaboraciones PRIMARY KEY (CODIGO_PROYECTOS, NIF_COLABORADOR),
CONSTRAINT fk1_proyectos_col FOREIGN KEY (CODIGO_PROYECTOS) REFERENCES PROYECTOS (CODIGO),
CONSTRAINT fk2_colaboradores_col FOREIGN KEY (NIF_COLABORADOR) REFERENCES COLABORADORES (NIF)
);
COMMIT;

CREATE TABLE TIPOS_DE_PAGO (
CODIGO NUMBER,
DESCRIPCION VARCHAR2(20),
-- RESTRICCIONES CLAVE PRIMARIA Y FORANEAS
CONSTRAINT pk_tipos_de_pago PRIMARY KEY (CODIGO)
);
COMMIT;

CREATE TABLE PAGOS (
NUMERO NUMBER,
CONCEPTO VARCHAR2(20),
IMPORTE NUMBER,
FECHA DATE,
CODIGO_TIPO_DE_PAGO NUMBER,
CODIGO_PROYECTO NUMBER,
NIF_COLABORADOR NUMBER,
-- RESTRICCIONES CLAVE PRIMARIA Y FORANEAS
CONSTRAINT pk_pagos PRIMARY KEY (NUMERO),
CONSTRAINT fk1_tipos_de_pago_pa FOREIGN KEY (CODIGO_TIPO_DE_PAGO) REFERENCES TIPOS_DE_PAGO (CODIGO),
CONSTRAINT fk2_proyectos_pa FOREIGN KEY (CODIGO_PROYECTO) REFERENCES PROYECTOS (CODIGO),
CONSTRAINT fk3_colaboradores_pa FOREIGN KEY (NIF_COLABORADOR) REFERENCES COLABORADORES (NIF),
-- RESTRICCIONES VARIAS
CONSTRAINT ck_importe CHECK (IMPORTE BETWEEN 0 AND 25000)
);
COMMIT;

ALTER TABLE PAGOS ADD CONSTRAINT ob_pagos NOT NULL (IMPORTE);
COMMIT;











